### ISSUE TITLE
Crash in AS preview and at runtime while inflating SegmentedGroup

### ISSUE THREAD

**Issue by mschuh** [Kaopiz/android-segmented-control#73]
Hello.

I tried to use your library in the simplest way possible, i.e. as in the main page example:

```
<info.hoang8f.android.segmented.SegmentedGroup
            xmlns:segmentedgroup="http://schemas.android.com/apk/res-auto"
            android:id="@+id/segmented2"
            android:layout_width="0dp"
            android:layout_weight="1"
            android:layout_height="wrap_content"
            android:layout_margin="10dp"
            android:orientation="horizontal"
            android:background="@color/backgroundLight"
            segmentedgroup:sc_border_width="2dp"
            segmentedgroup:sc_corner_radius="10dp">

            <RadioButton
                android:id="@+id/button21"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:text="One"
                style="@style/RadioButton" />

            <RadioButton
                android:id="@+id/button22"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:text="Two"
                style="@style/RadioButton" />
        </info.hoang8f.android.segmented.SegmentedGroup>
```

This is causing errors in preview and at runtime:

```
java.lang.ClassCastException: android.graphics.drawable.BitmapDrawable cannot be cast to android.graphics.drawable.GradientDrawable
                                                                                   at info.hoang8f.android.segmented.SegmentedGroup.updateBackground(SegmentedGroup.java:129)
                                                                                   at info.hoang8f.android.segmented.SegmentedGroup.updateBackground(SegmentedGroup.java:98)
                                                                                   at info.hoang8f.android.segmented.SegmentedGroup.onFinishInflate(SegmentedGroup.java:80)
                                                                                   at android.view.LayoutInflater.rInflate(LayoutInflater.java:826)
                                                                                   at android.view.LayoutInflater.rInflate(LayoutInflater.java:821)
                                                                                   at android.view.LayoutInflater.rInflate(LayoutInflater.java:821)
                                                                                   at android.view.LayoutInflater.inflate(LayoutInflater.java:511)
                                                                                   at android.view.LayoutInflater.inflate(LayoutInflater.java:415)
                                                                                   at br.skydrones.skydronescapture.view.missionplanner.SettingsFragment.onCreateView(SettingsFragment.java:68)
                                                                                   at android.support.v4.app.Fragment.performCreateView(Fragment.java:2189)
                                                                                   at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1299)
                                                                                   at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1528)
                                                                                   at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1595)
                                                                                   at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:757)
                                                                                   at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2355)
                                                                                   at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2146)
                                                                                   at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2098)
                                                                                   at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2008)
                                                                                   at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:710)
                                                                                   at android.os.Handler.handleCallback(Handler.java:739)
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                   at android.os.Looper.loop(Looper.java:145)
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:6126)
                                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                                   at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
```

If this is already solved in latest version why it isn't pushed to maven?
By the way, I'm using `compile 'info.hoang8f:android-segmented:1.0.6'` in my gradle file.

**Comment by LunevNF** [comment]
Same problem
